### ISSUE TITLE
Error + State of demo

### ISSUE THREAD

**Issue by lightice11** [Factual/factual-ios-sdk-demo#4]
I realize that the last activity in this repo was ~2 years ago, but the project is littered with warnings and errors...

![image](http://i60.tinypic.com/25yx6xf.png)

Just going to leave this here if anyone from Factual wants to fix it, but I can see if it's not a huge priority with the upcoming release of the new API.

**Comment by yoshimotob** [comment]
Won't fix -- we're deprecating this project and will be launching a new SDK
